name: Traffic Analysis Automation

on:
  schedule:
    - cron: "0 */2 * * *"  # Runs every 2 hours # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Debug Environment Variables
        run: env  # Prints all available environment variables for debugging

      - name: Run Traffic Analysis Script
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: node App.js